{% set name = "reikna" %}
{% set version = "0.7.2" %}
{% set sha256 = "c52f5ae13e35284feda8f6b67c0d6223c02c0292b1495969cf7a42f547b3fc18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip

  run:
    - python
    - mako >=0.8.0
    - numpy >=1.6.0
    - funcsigs >=0.3
    # Optional
    # - pycuda
    # - pyopencl

test:
  imports:
    - reikna
    - reikna.algorithms
    - reikna.cbrng
    - reikna.cluda
    - reikna.core
    - reikna.fft
    - reikna.helpers
    - reikna.linalg

about:
  home: http://github.com/fjarri/reikna
  license: MIT
  license_file: LICENSE.txt
  summary: GPGPU algorithms for PyCUDA and PyOpenCL

  doc_url: http://reikna.publicfields.net/
  dev_url: https://github.com/fjarri/reikna

extra:
  recipe-maintainers:
    - jakirkham
