travis:
  secure:
    BINSTAR_TOKEN: f0Vd8E/csLFtnNNtGPYB+ALs0/D5nHmCe9i7lRk/QqaEBDDvzXMu5BJSTQkTD+PI/KwGS6I+ZsBSjPkY7nA5YCLWmxYEO5h7n9vQqUIbfQtwNjp3qDWLNk7sHquFXorBlLjJxoMFwLicf10gxHiSDjg5lIMSZuDNrxXEiGJW15HirrXi9IOev9/HmZaMXzM9topK8hKb2y2sVOQWK60oIhNvZhSyKGIE/BIXbMWdYwK0kzsUjNcLWMDTVJDA28Bg7JjfpXpq0IEzFbE0amWzqGyb4qgSjsKPQSrTPnSvjD+1SaTjUUI+vPdD5dMcqayE5kiYcsXEGGQpO/d3uwc106qO5X/OnSu2t6Io9Daan3oBumkDUKNeC8jdQ1tZJLNhZ5iqUO9S4bAWRWpY8mGsgq4oGnj6qROv0TjuF2Q34ASy7ctgEv/lRtgxok4w0i9aJmQCy8HP7XQFH2OPl6PdbeBAcJa0NmtupS8R8N1DUYbx7OHtY/k/ZMoP+q5XBfhvdRlHGhmBbKYS49Hs8sVavWpITEjoaNfLeA61hdnJhP3aApne2LoqfWYRptA2zxT9YiwrHkwgxhxe3phy7Vi2UUDbLrH8NHWhyD9BqVcu/Q1jUrlAaFXiruJkhthcdRv5Qv/XPa8Zy3u+4Rsj3RGpzZYg55g4QWfznxW1kmlL2cc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
