travis:
  secure:
    BINSTAR_TOKEN: b8hwvmtbWOjnC7n15z/QFrcUn97bfYj2wXz7PzvUx0HGv6D/W5qUAu6gBMU4HrZ/T5Kcak+ljeDT6xKBxnr9bdQyqI+zdhmbYjJbNUk1uusu7lq6OUhSUogevTWeO4QgJzC5/Sb5QoZKU/0uuMtVFeHcjMypO+iMX0+2p9U6pl8EKq3OaB4yGjMfBF4GxEs4GlIF2z+2BJZS9JcjBARyP0y+V3KKzGW976r3alMZYHGNuNz3id0nFWo2EPuthTWQRZifFy5ES1f0fbuIksaJEw3+dX4eQpTCf+S3dwrBVzWAQ8t2CBsmWbAE3hQaZMDVYla2f4Ai9aWf9qHH0as6xsRRV/KwzFddG1k64reHy2OK5eoCL/T2Ddn0HmyrbKZsVOBRitbWWKnP4zrBHgUZ4lKUiUSs2PhXOY5R8/sTkSjdGOG5Fv6q2AL88M/6O8d0b7lXpKO/BKjRTulGLKFNjxZ82XNKQqwix8DW7ikXGf9bHq4M3+yoJXrJbzQwwz6W5MGXyggFIDB0KsrvhYWyRObINxbaTMeVH3g0Bwgmp3pJVPpZZq2tFYCoEklGxhzzbytMSGvwuC553RwRKarS1zaACEKOzyWPJYBLeIkyxk3Fy9x4cLWF7CH1NKThga2L2siEL1Gy3NYHcO1U8Zfr1Qjpr7yhboCXZpkIBz1B83E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
